/**
 * Rathole Config Management
 *
 * Manages the rathole server configuration file for dynamic client registration.
 * Uses hot-reload: rathole automatically picks up config changes without restart.
 *
 * Config format (TOML):
 * ```
 * [server]
 * bind_addr = "0.0.0.0:2333"
 * heartbeat_interval = 30
 *
 * [server.services.{hash}]
 * token = "{token}"
 * bind_addr = "0.0.0.0:{port}"
 * ```
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// =============================================================================
// Configuration
// =============================================================================

const CONFIG_DIR = process.env.RATHOLE_CONFIG_DIR || '/etc/rathole';
const CONFIG_FILE = join(CONFIG_DIR, 'server.toml');
const CONTROL_PORT = process.env.RATHOLE_CONTROL_PORT || '2333';

// Base port for dynamic service allocation
// Each new service gets the next available port starting from this
const BASE_SERVICE_PORT = parseInt(process.env.BASE_SERVICE_PORT || '10000', 10);

// =============================================================================
// Types
// =============================================================================

export interface ServiceEntry {
  hash: string;
  token: string;
  port: number;
}

export interface RatholeConfig {
  controlPort: string;
  heartbeatInterval: number;
  services: Map<string, ServiceEntry>;
}

// =============================================================================
// Config Management
// =============================================================================

/**
 * Parse existing rathole config file.
 * Returns empty config if file doesn't exist.
 */
export function loadConfig(): RatholeConfig {
  const config: RatholeConfig = {
    controlPort: CONTROL_PORT,
    heartbeatInterval: 30,
    services: new Map(),
  };

  if (!existsSync(CONFIG_FILE)) {
    return config;
  }

  try {
    const content = readFileSync(CONFIG_FILE, 'utf-8');
    // Simple TOML parsing for our known format
    // For production, consider using a proper TOML library

    const lines = content.split('\n');
    let currentService: string | null = null;
    let currentEntry: Partial<ServiceEntry> = {};

    for (const line of lines) {
      const trimmed = line.trim();

      // Parse [server.services.{hash}]
      const serviceMatch = trimmed.match(/^\[server\.services\.([^\]]+)\]$/);
      if (serviceMatch) {
        // Save previous service if any
        if (currentService && currentEntry.token && currentEntry.port) {
          config.services.set(currentService, {
            hash: currentService,
            token: currentEntry.token,
            port: currentEntry.port,
          });
        }
        currentService = serviceMatch[1];
        currentEntry = { hash: currentService };
        continue;
      }

      // Parse token = "..."
      const tokenMatch = trimmed.match(/^token\s*=\s*"([^"]+)"$/);
      if (tokenMatch && currentService) {
        currentEntry.token = tokenMatch[1];
        continue;
      }

      // Parse bind_addr = "0.0.0.0:{port}"
      const bindMatch = trimmed.match(/^bind_addr\s*=\s*"0\.0\.0\.0:(\d+)"$/);
      if (bindMatch && currentService) {
        currentEntry.port = parseInt(bindMatch[1], 10);
        continue;
      }
    }

    // Save last service
    if (currentService && currentEntry.token && currentEntry.port) {
      config.services.set(currentService, {
        hash: currentService,
        token: currentEntry.token,
        port: currentEntry.port,
      });
    }
  } catch (error) {
    console.error('[Config] Failed to parse config file:', error);
  }

  return config;
}

/**
 * Write rathole config to file.
 * rathole will automatically pick up changes via hot-reload.
 */
export function saveConfig(config: RatholeConfig): void {
  const lines: string[] = [
    '# Rathole Server Configuration',
    '# Auto-generated by cast-tunnel-server',
    '# Changes are hot-reloaded automatically',
    '',
    '[server]',
    `bind_addr = "0.0.0.0:${config.controlPort}"`,
    `heartbeat_interval = ${config.heartbeatInterval}`,
    '',
  ];

  // Add service entries
  for (const [hash, service] of config.services) {
    lines.push(`[server.services.${hash}]`);
    lines.push(`token = "${service.token}"`);
    lines.push(`bind_addr = "0.0.0.0:${service.port}"`);
    lines.push('');
  }

  writeFileSync(CONFIG_FILE, lines.join('\n'), 'utf-8');
  console.log(`[Config] Saved config with ${config.services.size} services`);
}

/**
 * Register a new tunnel client.
 * Assigns a port and adds to config file.
 *
 * @param hash - Container's tunnel hash
 * @param token - Auth token for this service
 * @returns The assigned service entry
 */
export function registerService(hash: string, token: string): ServiceEntry {
  const config = loadConfig();

  // Check if already registered
  const existing = config.services.get(hash);
  if (existing) {
    console.log(`[Config] Service ${hash} already registered on port ${existing.port}`);
    return existing;
  }

  // Find next available port
  let port = BASE_SERVICE_PORT;
  const usedPorts = new Set([...config.services.values()].map((s) => s.port));
  while (usedPorts.has(port)) {
    port++;
  }

  const entry: ServiceEntry = { hash, token, port };
  config.services.set(hash, entry);
  saveConfig(config);

  console.log(`[Config] Registered service ${hash} on port ${port}`);
  return entry;
}

/**
 * Unregister a tunnel client.
 * Removes from config file.
 *
 * @param hash - Container's tunnel hash
 * @returns true if removed, false if not found
 */
export function unregisterService(hash: string): boolean {
  const config = loadConfig();

  if (!config.services.has(hash)) {
    console.log(`[Config] Service ${hash} not found`);
    return false;
  }

  config.services.delete(hash);
  saveConfig(config);

  console.log(`[Config] Unregistered service ${hash}`);
  return true;
}

/**
 * Get service entry by hash.
 */
export function getService(hash: string): ServiceEntry | null {
  const config = loadConfig();
  return config.services.get(hash) || null;
}

/**
 * List all registered services.
 */
export function listServices(): ServiceEntry[] {
  const config = loadConfig();
  return [...config.services.values()];
}

/**
 * Initialize config file with base server settings.
 * Called on startup to ensure config exists.
 *
 * Note: rathole requires at least one service in the config to start.
 * We add a placeholder service that binds to localhost only (unreachable).
 */
export function initializeConfig(): void {
  if (existsSync(CONFIG_FILE)) {
    console.log(`[Config] Using existing config at ${CONFIG_FILE}`);
    return;
  }

  const config: RatholeConfig = {
    controlPort: CONTROL_PORT,
    heartbeatInterval: 30,
    services: new Map(),
  };

  // Add placeholder service - rathole requires at least one service to start
  // This binds to localhost only and uses an unusable token, so it's harmless
  config.services.set('_placeholder', {
    hash: '_placeholder',
    token: 'placeholder-not-used-token',
    port: 19999,
  });

  saveConfig(config);
  console.log(`[Config] Initialized new config at ${CONFIG_FILE}`);
}
